apiVersion: apps/v1 # 
kind: Deployment
metadata:
  name: vanapinginx-deployment
spec:
  selector:
    matchLabels:
      app: vanvia
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: vanvia
    spec:
      containers:
      - name: vanapi
        image: htnawsaj/vanapi:intial
        ports:
        - containerPort: 80
---          
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: vanvia
#  name: vanvia-svc
#  namespace: default
#spec:
#  type: NodePort  # use ClusterIP as type here
#  ports:
#    - port: 80
#  selector:
#    app: vanvia
